"""
Read and write profiles
"""

import numpy as np
import matplotlib.pyplot as plt
from farpy._Profiles._profiles_header import profilesOrderInputs, \
    profilesOrderDat, profilesOrderExDat
from farpy._Plotting._settings import axis_beauty

class Profiles:
    """
    Parent class for the profiles, just contains the plot and header
    """

    def _init_(self):
        self.file = None
        self.header = {}
        self.data = []

    def plot(self, var='te', ax=None, ax_params={}, line_params={}):
        """
        Plot a given profile

        Jose Rueda: jrrueda@us.es

        @param var: variable to plot
        @param ax: axes where to plot
        @param ax_params: parameters for the axis beauty
        @param line_params: line parameters for the plt.plot function
        """
        # --- Get the index:
        column_to_plot = self.header['info'][var]['i']
        rho_colum = self.header['info']['rho']['i']
        # --- Default plotting options
        ax_options = {
            'grid': 'both',
            'xlabel': self.header['info']['rho']['shortName'],
            'ylabel':  self.header['info'][var]['shortName']
            + self.header['info'][var]['units'],
        }
        ax_options.update(ax_params)
        # --- Create the axes
        if ax is None:
            fig, ax = plt.subplots()
            created = True
        else:
            created = False
        ax.plot(self.data[:, rho_colum], self.data[:, column_to_plot],
                **line_params)
        # axis beauty:
        if created:
            ax = axis_beauty(ax, ax_options)


class ProfilesInput(Profiles):
    """
    Read and write the input plasma profiles for the Far3D code.

    Jose Rueda: jrrueda@us.es

    @ToDo: The writting part
    """

    def __init__(self, filename=None, DIIID_u=0, alpha_on=0):
        """
        Initialize the object.

        Jose Rueda: jrrueda@us.es

        @param filename: filename for the ASCII file with the profiles, in
            far3D format. If None, the object will be initialised as empty
            ideal if you want to will it with your own profiles and then write
            the file
        @param DIIID_u: namelist variable of the simulation, to decide the units
        @param alpha_on: namelist variable of the simulation, to include a
            second specie
        """
        self.file = filename
        # --- Initilise the profiles
        ## Field at the magnetic axis [in T]
        self.bt0 = 0.0
        ## Major radius
        self.rmajr = 0.0
        ## Minor radius
        self.rminr = 0.0
        ## Average elongation
        self.kappa = 0.0
        ## Average triangularity
        self.delta = 0.0
        ## Main impurity
        self.mainImpurity = ''
        ## Ion mass over protton mass
        self.mi_mp = 0.0
        ## beta at axis
        self.beta0 = 0.0
        self.Rmax = 0.0

        ## Header
        self.header = {'info': profilesOrderInputs[DIIID_u][alpha_on]}

        # --- Read the profiles
        if filename is not None:
            with open(filename) as fid:
                dummy = fid.readline()
                dummy = fid.readline()
                self.bt0 = float(fid.readline())
                dummy = fid.readline()
                self.rmajr = float(fid.readline())
                dummy = fid.readline()
                self.rminr = float(fid.readline())
                dummy = fid.readline()
                self.kappa = float(fid.readline())
                dummy = fid.readline()
                self.delta = float(fid.readline())
                dummy = fid.readline()
                self.mainImpurity = fid.readline()
                dummy = fid.readline()
                self.mi_mp = float(fid.readline())
                macabro = fid.readline()
                elements = macabro.split('=')
                self.beta0 = float(elements[1].split(',')[0])
                self.Rmax = float(elements[2])
                self.eps = self.rminr / self.rmajr
                # Finally end of header, uff
            # Now just read and store the profiles
            self.data = np.loadtxt(filename, skiprows=19)


class ProfilesOutputDat(Profiles):
    """
    Read and handle the profiles.dat file generated by FAR3d

    Jose Rueda: jrrueda@us.es
    """

    def __init__(self, filename=None, ext_prof: int = 0, alpha_on: int = 0):
        """Initialise the class."""
        self.file = filename
        data = np.loadtxt(filename, skiprows=1)
        nr, nc = data.shape
        if ext_prof == 0 and nc != 14:
            print('Was expecting 14 but I got %i columns' % nc)
            raise Exception('Wrong file?')
        if ext_prof == 1 and alpha_on == 0 and nc != 17:
            print('Was expecting 16 but I got %i columns' % nc)
            raise Exception('Wrong file?')
        if ext_prof == 1 and alpha_on == 1 and nc != 19:
            print('Was expecting 18 but I got %i columns' % nc)
            raise Exception('Wrong file?')
        self.data = data
        self.header = {'info': profilesOrderDat[ext_prof][alpha_on]}


class ProfilesOutputExDat(Profiles):
    """
    Read and handle the profiles_ex.dat file generated by FAR3d

    Jose Rueda: jrrueda@us.es
    """

    def __init__(self, filename=None, alpha_on: int = 0):
        self.file = filename
        data = np.loadtxt(filename, skiprows=1)
        nr, nc = data.shape
        if alpha_on == 0 and nc != 11:
            raise Exception('Wrong file?')
        if alpha_on == 1 and nc != 13:
            raise Exception('Wrong file?')
        self.data = data
        self.header = {'info': profilesOrderExDat[alpha_on]}
